version: '3.8'

services:
  event-service:
    container_name: event-service
    build:
      context: ./Eventsir.Services.Events
      dockerfile: dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8080;http://+:8081
      - Mongo__ConnectionString=mongodb://host.docker.internal:27017/
      - RabbitMQ__Hostname=rabbitmq
    depends_on:
      - mongodb
    networks:
      - my-network

  mongodb:
    container_name: mongoDb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

  rabbitMq:
    container_name: rabbitMQ
    image: rabbitmq:3.13-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit-data:/data/db
    networks:
      - my-network
volumes:
  mongo-data:
  rabbit-data:

networks:
  my-network:
    driver: bridge
