version: '3.8'

services:
  event-service:
    container_name: event-service
    build:
      context: ./Eventsir.Services.Events
      dockerfile: dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb
    networks:
      - my-network

  ticket-service:
    container_name: ticket-service
    build:
      context: ./Eventsir.Services.Tickets
      dockerfile: dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb
    networks:
      - my-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

volumes:
  mongo-data:

networks:
  my-network:
    driver: bridge
