#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /ap
EXPOSE 80
EXPOSE 443


FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["src/Eventsir.Services.Tickets.API/Eventsir.Services.Tickets.API.csproj", "src/Eventsir.Services.Tickets.API/"]
COPY ["src/Eventsir.Services.Tickets.Application/Eventsir.Services.Tickets.Application.csproj", "src/Eventsir.Services.Tickets.Application/"]
COPY ["src/Eventsir.Services.Tickets.Domain/Eventsir.Services.Tickets.Domain.csproj", "src/Eventsir.Services.Tickets.Domain/"]
COPY ["src/Eventsir.Services.Tickets.Infrastructure/Eventsir.Services.Tickets.Infrastructure.csproj", "src/Eventsir.Services.Tickets.Infrastructure/"]
COPY ["tests/Eventsir.Services.Tickets.UnitTests/Eventsir.Services.Tickets.UnitTests.csproj", "tests/Eventsir.Services.Tickets.Infrastructure/"]
RUN dotnet restore "src/Eventsir.Services.Tickets.API/Eventsir.Services.Tickets.API.csproj"
COPY . .
WORKDIR "/src/src/Eventsir.Services.Tickets.API"
RUN dotnet build "Eventsir.Services.Tickets.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Eventsir.Services.Tickets.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Eventsir.Services.Tickets.API.dll"]